//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;age&quot;;&quot;job&quot;;&quot;marital&quot;;&quot;education&quot;;&quot;default&quot;;&quot;balance&quot;;&quot;housing&quot;;&quot;loan&quot;;&quot;contact&quot;;&quot;day&quot;;&quot;month&quot;;&quot;duration&quot;;&quot;campaign&quot;;&quot;pdays&quot;;&quot;previous&quot;;&quot;poutcome&quot;;&quot;y&quot;
        ///30;&quot;unemployed&quot;;&quot;married&quot;;&quot;primary&quot;;&quot;no&quot;;1787;&quot;no&quot;;&quot;no&quot;;&quot;cellular&quot;;19;&quot;oct&quot;;79;1;-1;0;&quot;unknown&quot;;&quot;no&quot;
        ///30;&quot;management&quot;;&quot;married&quot;;&quot;tertiary&quot;;&quot;no&quot;;1476;&quot;yes&quot;;&quot;yes&quot;;&quot;unknown&quot;;3;&quot;jun&quot;;199;4;-1;0;&quot;unknown&quot;;&quot;no&quot;
        ///68;&quot;retired&quot;;&quot;divorced&quot;;&quot;secondary&quot;;&quot;no&quot;;4189;&quot;no&quot;;&quot;no&quot;;&quot;telephone&quot;;14;&quot;jul&quot;;897;2;-1;0;&quot;unknown&quot;;&quot;yes&quot;
        ///31;&quot;technician&quot;;&quot;married&quot;;&quot;secondary&quot;;&quot;no&quot;;171;&quot....
        /// </summary>
        internal static string bank1 {
            get {
                return ResourceManager.GetString("bank1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MWG;NWG;KWG;MDIMC;NDIMC;MDIMA;NDIMB;KWI;VWM;VWN;STRM;STRN;SA;SB;Run1 (ms);Run2 (ms);Run3 (ms);Run4 (ms)
        ///16;16;16;8;8;8;8;2;1;1;0;0;0;0;115,26;115,87;118,55;115,8
        ///16;16;16;8;8;8;8;2;1;1;0;0;0;1;78,13;78,25;79,25;79,19
        ///16;16;16;8;8;8;8;2;1;1;0;0;1;0;79,84;80,69;80,76;80,97
        ///16;16;16;8;8;8;8;2;1;1;0;0;1;1;84,32;89,9;86,75;85,58
        ///16;16;16;8;8;8;8;2;1;1;0;1;0;0;115,13;121,98;122,73;114,81
        ///16;16;16;8;8;8;8;2;1;1;0;1;0;1;81,1;82,41;87,01;82,14
        ///16;16;16;8;8;8;8;2;1;1;0;1;1;0;83,31;82,86;88,6;82,97
        ///16;16;16;8;8;8;8;2; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string sgemm_product {
            get {
                return ResourceManager.GetString("sgemm_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MWG;NWG;KWG;MDIMC;NDIMC;MDIMA;NDIMB;KWI;VWM;VWN;STRM;STRN;SA;SB;Run1 (ms);Run2 (ms);Run3 (ms);Run4 (ms)
        ///128;64;32;16;8;16;32;8;8;1;0;0;0;0;251,19;251,76;251,13;251,89
        ///128;64;32;16;8;16;32;8;8;1;0;0;0;1;150,43;151,5;151,53;151,25
        ///128;64;32;16;8;16;32;8;8;1;0;0;1;0;209,87;211,31;209,65;210,12
        ///128;64;32;16;8;16;32;8;8;1;0;0;1;1;214,28;215,14;214,4;214,31
        ///128;64;32;16;8;16;32;8;8;1;0;1;0;0;259,4;261,15;259,74;259,87
        ///128;64;32;16;8;16;32;8;8;1;0;1;0;1;143,27;142,3;141,87;142,39
        ///128;64;32;16;8;16;32;8;8;1; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string sgemm_product_real {
            get {
                return ResourceManager.GetString("sgemm_product_real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MWG;NWG;KWG;MDIMC;NDIMC;MDIMA;NDIMB;KWI;VWM;VWN;STRM;STRN;SA;SB;Run1 (ms);Run2 (ms);Run3 (ms);Run4 (ms)
        ///16;16;16;8;8;8;8;2;1;1;0;0;0;0;115,26;115,87;118,55;115,8
        ///16;16;16;8;8;8;8;2;1;1;0;0;0;1;78,13;78,25;79,25;79,19
        ///16;16;16;8;8;8;8;2;1;1;0;0;1;0;79,84;80,69;80,76;80,97
        ///16;16;16;8;8;8;8;2;1;1;0;0;1;1;84,32;89,9;86,75;85,58
        ///16;16;16;8;8;8;8;2;1;1;0;1;0;0;115,13;121,98;122,73;114,81
        ///16;16;16;8;8;8;8;2;1;1;0;1;0;1;81,1;82,41;87,01;82,14
        ///16;16;16;8;8;8;8;2;1;1;0;1;1;0;83,31;82,86;88,6;82,97
        ///16;16;16;8; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string sgemm_product_study {
            get {
                return ResourceManager.GetString("sgemm_product_study", resourceCulture);
            }
        }
    }
}
