//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MWG;NWG;KWG;MDIMC;NDIMC;MDIMA;NDIMB;KWI;VWM;VWN;STRM;STRN;SA;SB;Run1 (ms);Run2 (ms);Run3 (ms);Run4 (ms)
        ///128;64;32;16;8;16;32;8;8;1;0;0;0;0;251,19;251,76;251,13;251,89
        ///128;64;32;16;8;16;32;8;8;1;0;0;0;1;150,43;151,5;151,53;151,25
        ///128;64;32;16;8;16;32;8;8;1;0;0;1;0;209,87;211,31;209,65;210,12
        ///128;64;32;16;8;16;32;8;8;1;0;0;1;1;214,28;215,14;214,4;214,31
        ///128;64;32;16;8;16;32;8;8;1;0;1;0;0;259,4;261,15;259,74;259,87
        ///128;64;32;16;8;16;32;8;8;1;0;1;0;1;143,27;142,3;141,87;142,39
        ///128;64;32;16;8;16;32;8;8;1; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string sgemm_product_real {
            get {
                return ResourceManager.GetString("sgemm_product_real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MWG;NWG;KWG;MDIMC;NDIMC;MDIMA;NDIMB;KWI;VWM;VWN;STRM;STRN;SA;SB;Run1 (ms);Run2 (ms);Run3 (ms);Run4 (ms)
        ///16;16;16;8;8;8;8;2;1;1;0;0;0;0;115,26;115,87;118,55;115,8
        ///16;16;16;8;8;8;8;2;1;1;0;0;0;1;78,13;78,25;79,25;79,19
        ///16;16;16;8;8;8;8;2;1;1;0;0;1;0;79,84;80,69;80,76;80,97
        ///16;16;16;8;8;8;8;2;1;1;0;0;1;1;84,32;89,9;86,75;85,58
        ///16;16;16;8;8;8;8;2;1;1;0;1;0;0;115,13;121,98;122,73;114,81
        ///16;16;16;8;8;8;8;2;1;1;0;1;0;1;81,1;82,41;87,01;82,14
        ///16;16;16;8;8;8;8;2;1;1;0;1;1;0;83,31;82,86;88,6;82,97
        ///16;16;16;8; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string sgemm_product_study {
            get {
                return ResourceManager.GetString("sgemm_product_study", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.0;0.0.1;5.0;6.0;7.0;y
        ///440.0;15.753;17.167;0.087;-0.518;-0.316
        ///429.0;16.240000000000002;17.125;0.23;-0.723;-0.501
        ///451.0;15.312999999999999;17.021;-0.121;-0.39799999999999996;-0.307
        ///407.0;16.569000000000006;16.956;0.162;-0.853;-0.364
        ///418.0;16.414;16.99;0.18;-0.831;-0.47100000000000003
        ///396.0;16.792;17.069000000000006;0.18600000000000005;-0.9470000000000001;-0.248
        ///900.0;16.015;16.016;-0.846;-0.46799999999999997;-0.858
        ///397.0;17.430999999999994;16.961;-0.075;0.14800000000000002;-0.893
        ///922.0;15.882;15.9 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string X_checking {
            get {
                return ResourceManager.GetString("X_checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.0;0.0.1;5.0;6.0;7.0;y
        ///911.0;15.937999999999999;16.049;-0.87;-0.524;-0.98
        ///441.0;16.817;16.582;-0.447;-0.085;-0.904
        ///430.0;16.848;16.753;-0.522;-0.005;-0.821
        ///408.0;17.340999999999998;17.045;-0.149;0.184;-0.927
        ///363.0;16.406;16.723;0.695;-0.982;-1.433
        ///452.0;16.904;16.497;-0.29600000000000004;-0.067;-0.973
        ///341.0;16.732;17.194000000000006;0.892;-1.2930000000000001;-1.033
        ///374.0;16.219;16.651;0.615;-1.082;-1.272
        ///889.0;15.999;15.972;-0.825;-0.39;-0.898
        ///66.0;15.898;17.434;0.6629999999999999;0.0360000000000 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string X_teaching {
            get {
                return ResourceManager.GetString("X_teaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.0;0.0.1;5.0;6.0;7.0;Y
        ///157.0;18.43;16.961;-0.231;0.955;0
        ///678.0;15.911;16.018;-0.35;СЏРЅРІ.77;0
        ///142.0;17.021;17.323;-0.212;1.286;0
        ///588.0;17.215999999999998;17.342;0.017;0.589;0
        ///97.0;15.324000000000002;17.493;0.049;0.076;0
        ///884.0;17.033;17.505;-0.004;-0.418;0
        ///642.0;17.С„РµРІ;17.039;0.191;0.044000000000000004;0
        ///103.0;17.276;16.548;-0.08;0.4;0
        ///32.0;17.141;17.39;-0.608;0.956;0
        ///599.0;17.45;16.217;0.051;0.723;0
        ///94.0;16.945999999999998;16.299;-0.26899999999999996;0.45899999999999996;0
        ///105.0;16.908;16.19 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string X_test {
            get {
                return ResourceManager.GetString("X_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.0;0.0.1;5.0;6.0;7.0;y
        ///440.0;15.753;17.167;0.087;-0.518;-0.316
        ///429.0;16.240000000000002;17.125;0.23;-0.723;-0.501
        ///451.0;15.312999999999999;17.021;-0.121;-0.39799999999999996;-0.307
        ///407.0;16.569000000000006;16.956;0.162;-0.853;-0.364
        ///418.0;16.414;16.99;0.18;-0.831;-0.47100000000000003
        ///396.0;16.792;17.069000000000006;0.18600000000000005;-0.9470000000000001;-0.248
        ///900.0;16.015;16.016;-0.846;-0.46799999999999997;-0.858
        ///397.0;17.430999999999994;16.961;-0.075;0.14800000000000002;-0.893
        ///922.0;15.882;15.9 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string X_train {
            get {
                return ResourceManager.GetString("X_train", resourceCulture);
            }
        }
    }
}
